spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/java_focus_group_demo"
    username: "java_focus_group_demo"
    password: "java_focus_group_demo"
    driver-class-name: "org.postgresql.Driver"
    initialization-mode: "always"
  jpa:
    show-sql: "true"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "validate"
