spring:
  datasource:
    url: "jdbc:postgresql://database:5432/java_focus_group_demo"
    username: "postgres"
    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: "true"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "validate"
